---
# tasks file for genkey

- name: Generate a new ssh Key
  shell: ssh-keygen -t rsa -b {{ ssh_key_bits }} -N "{{ passphrase }}" -q -f {{ ssh_key_path }} -C {{ ssh_key_comment }}
  args:
    creates: '{{ ssh_key_path }}'
  delegate_to: localhost

- name: Store then value of the public ssh key
  set_fact:
    ssh_connection_key: "{{ lookup('file', ssh_key_path + '.pub') }}"
