---
# tasks file for turnkey


- name: Store then value of the public ssh key
  set_fact:
    ssh_connection_key: "{{ lookup('file', ssh_key_path + '.pub') }}"
  delegate_to: localhost
  delegate_facts: False

- name: Set Authorized key(s) to the authorized keys file
  become: yes
  become_user: root
  authorized_key:
    exclusive: '{{ is_exclusive }}'
    user: '{{ ssh_host_user }}'
    state: present
    key: '{{ ssh_connection_key }}'
